version: '3.8'

# Custom networks for better isolation
networks:
  home-lab:
    driver: bridge
    name: home-lab

# Persistent volumes for data persistence
volumes:
  ollama:
    name: ollama-data
  open-webui:
    name: openwebui-data
  littlellm-db:
    name: littlellm-db

services:
  # Ollama - Local LLM server
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    networks:
      - home-lab
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - OLLAMA_HOST=0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Open WebUI - Web interface for Ollama
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    ports:
      - "3000:8080"
    volumes:
      - open-webui:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY:-your-secret-key-here}
    depends_on:
      ollama:
        condition: service_healthy
    networks:
      - home-lab
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 5s
      retries: 3

  # LittleLLM - API key management
  littlellm:
    image: berriai/littlellm:latest
    container_name: littlellm
    restart: unless-stopped
    ports:
      - "4000:4000"
    volumes:
      - littlellm-db:/app/db
    environment:
      - DATABASE_URL=file:/app/db/littlellm.db
      - LITELIMIT_API_KEY=${LITELIMIT_API_KEY:-your-api-key-here}
      - NODE_ENV=production
    networks:
      - home-lab
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  # Watchtower - For automatic updates
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 3600 --cleanup --label-enable
    networks:
      - home-lab

  # Portainer - Container management UI (optional)
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - home-lab
