version: '3.8'

services:
  # Home Assistant: The brain of your smart home
  home-assistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: home-assistant
    ports:
      # Main port to access the web interface
      - "8123:8123"
    volumes:
      # Maps the configuration folder to your local machine
      - ./homeassistant_config:/config
    environment:
      # Sets the correct timezone for accurate automations
      - TZ=America/Sao_Paulo
    restart: unless-stopped
    # Uncomment the 'devices' section below if you need to pass USB devices, like a Zigbee/Z-Wave dongle
    # devices:
    #   - /dev/ttyACM0:/dev/ttyACM0

  # AdGuard Home: Network-wide ad-blocker and DNS server
  adguard-home:
    image: adguard/adguardhome
    container_name: adguard-home
    ports:
      # Port 53 for the DNS service (TCP and UDP)
      - "53:53/tcp"
      - "53:53/udp"
      # Port 8088 to access the AdGuard web interface (avoids conflicts with other applications)
      - "8088:80/tcp"
      # Optional ports for DNS over HTTPS and DNS over TLS
      - "443:443/tcp"
      - "853:853/tcp"
      # Optional ports if you want AdGuard to act as your DHCP server
      # - "67:67/udp"
      # - "68:68/udp"
    volumes:
      # Maps the work and configuration folders to your local machine
      - ./adguard_work:/opt/adguardhome/work
      - ./adguard_conf:/opt/adguardhome/conf
    restart: unless-stopped