version: '3.8'

networks:
  prod:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.1.0/27
  cacau:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.1.32/27

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer-server
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - prod
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data
    ports:
      - "8000:8000"
      - "9443:9443"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.local`)"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    networks:
      - prod
      - cacau
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    networks:
      - prod
      - cacau
    volumes:
      - open_webui_data:/app/backend/data
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434/api
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
    depends_on:
      - ollama
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webui.rule=Host(`ai.local`)"
      - "traefik.http.services.webui.loadbalancer.server.port=8080"

  littlellm:
    image: ghcr.io/berriai/littlellm:latest
    container_name: littlellm
    restart: unless-stopped
    networks:
      - prod
    volumes:
      - ./config:/app/config
      - ./keys:/app/keys:ro
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - CONFIG_PATH=/app/config/config.yaml
      - MASTER_KEY=${LITTLELLM_MASTER_KEY:-}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.littlellm.rule=Host(`llm.local`)"
      - "traefik.http.services.littlellm.loadbalancer.server.port=8000"

volumes:
  portainer_data:
  ollama_data:
  open_webui_data:
